project_id = "uslfzmfnkhkgklaoofny"

[functions.extract-line-items]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

	--##skhdbdmyrrpvgxkhytfm

[functions.auth-email-hook]
verify_jwt = false

[functions.stripe-invoice-webhook]
verify_jwt = false

[functions.create-public-invoice-payment]
verify_jwt = false

[functions.get-public-invoice]
verify_jwt = false
